# Generated by Django 6.0.2 on 2026-02-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDoctorMapping',
        ),
    ]
